spring:
  jpa:
    database-platform: cn.edu.pku.sei.sc.allen.util.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:allen.db
